export type CandidateStatus = "New" | "Shortlisted" | "Interview" | "Offer" | "Rejected";

export interface Candidate {
  id: string;
  name: string;
  role: string;
  location: string;
  experienceYears: number;
  skills: string[];
  status: CandidateStatus;
  appliedDate: string;
  initials: string;
  matchScore: number;
  summary: string;
}

export const CANDIDATES: Candidate[] = [
  {
    id: "1",
    name: "Sarah Chen",
    role: "Frontend Developer",
    location: "London",
    experienceYears: 4,
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS"],
    status: "Shortlisted",
    appliedDate: "2025-05-12",
    initials: "SC",
    matchScore: 91,
    summary: "4 years building React SPAs and Next.js apps. Strong TypeScript skills and experience with design systems.",
  },
  {
    id: "2",
    name: "Marcus Webb",
    role: "Backend Developer",
    location: "Manchester",
    experienceYears: 7,
    skills: ["Node.js", "PostgreSQL", "Docker", "AWS"],
    status: "Interview",
    appliedDate: "2025-05-10",
    initials: "MW",
    matchScore: 85,
    summary: "7 years backend engineering. Led migrations to microservices architecture at two scale-ups.",
  },
  {
    id: "3",
    name: "Priya Nair",
    role: "Full Stack Developer",
    location: "Remote",
    experienceYears: 5,
    skills: ["React", "Python", "Django", "PostgreSQL", "TypeScript"],
    status: "New",
    appliedDate: "2025-05-15",
    initials: "PN",
    matchScore: 88,
    summary: "5 years full-stack, primarily React + Django. Built data-heavy dashboards for fintech clients.",
  },
  {
    id: "4",
    name: "James Okafor",
    role: "Product Designer",
    location: "London",
    experienceYears: 6,
    skills: ["Figma", "User Research", "Prototyping", "Design Systems"],
    status: "Offer",
    appliedDate: "2025-04-28",
    initials: "JO",
    matchScore: 94,
    summary: "6 years product design. Established design systems at two Series B companies.",
  },
  {
    id: "5",
    name: "Lena Hoffmann",
    role: "Frontend Developer",
    location: "Remote",
    experienceYears: 2,
    skills: ["React", "JavaScript", "CSS", "Vue.js"],
    status: "New",
    appliedDate: "2025-05-16",
    initials: "LH",
    matchScore: 72,
    summary: "2 years frontend. Transitioned from graphic design — strong visual sensibility and CSS skills.",
  },
  {
    id: "6",
    name: "Daniel Torres",
    role: "Backend Developer",
    location: "London",
    experienceYears: 9,
    skills: ["Go", "Kubernetes", "gRPC", "AWS", "PostgreSQL"],
    status: "Rejected",
    appliedDate: "2025-05-02",
    initials: "DT",
    matchScore: 66,
    summary: "9 years backend. Deep Go expertise but limited web API experience for this role.",
  },
  {
    id: "7",
    name: "Amara Osei",
    role: "Full Stack Developer",
    location: "Birmingham",
    experienceYears: 3,
    skills: ["React", "Node.js", "MongoDB", "Express", "TypeScript"],
    status: "Shortlisted",
    appliedDate: "2025-05-11",
    initials: "AO",
    matchScore: 82,
    summary: "3 years full-stack with the MERN stack. Built two SaaS products from scratch.",
  },
  {
    id: "8",
    name: "Tom Finlay",
    role: "DevOps Engineer",
    location: "Edinburgh",
    experienceYears: 8,
    skills: ["Kubernetes", "Terraform", "AWS", "CI/CD", "Docker"],
    status: "Interview",
    appliedDate: "2025-05-07",
    initials: "TF",
    matchScore: 89,
    summary: "8 years DevOps. Managed infrastructure for companies scaling to millions of users.",
  },
  {
    id: "9",
    name: "Nina Petrova",
    role: "Product Manager",
    location: "London",
    experienceYears: 5,
    skills: ["Roadmapping", "Agile", "SQL", "Figma", "Analytics"],
    status: "New",
    appliedDate: "2025-05-14",
    initials: "NP",
    matchScore: 78,
    summary: "5 years PM in B2B SaaS. Comfortable bridging engineering and commercial teams.",
  },
  {
    id: "10",
    name: "Kwame Asante",
    role: "Frontend Developer",
    location: "London",
    experienceYears: 6,
    skills: ["React", "TypeScript", "GraphQL", "Performance", "Accessibility"],
    status: "Shortlisted",
    appliedDate: "2025-05-09",
    initials: "KA",
    matchScore: 93,
    summary: "6 years frontend. Specialist in performance optimisation and web accessibility.",
  },
  {
    id: "11",
    name: "Isla MacKay",
    role: "Product Designer",
    location: "Remote",
    experienceYears: 3,
    skills: ["Figma", "UX Writing", "User Testing", "Wireframing"],
    status: "Interview",
    appliedDate: "2025-05-06",
    initials: "IM",
    matchScore: 80,
    summary: "3 years UX/product design. Focused on zero-to-one product work at early-stage startups.",
  },
  {
    id: "12",
    name: "Rohan Mehta",
    role: "Backend Developer",
    location: "Manchester",
    experienceYears: 11,
    skills: ["Java", "Spring Boot", "Kafka", "Elasticsearch", "AWS"],
    status: "New",
    appliedDate: "2025-05-17",
    initials: "RM",
    matchScore: 76,
    summary: "11 years backend, primarily Java. Experienced in high-throughput event-driven systems.",
  },
  {
    id: "13",
    name: "Chloe Dubois",
    role: "Full Stack Developer",
    location: "London",
    experienceYears: 4,
    skills: ["Next.js", "TypeScript", "Prisma", "PostgreSQL", "tRPC"],
    status: "Shortlisted",
    appliedDate: "2025-05-08",
    initials: "CD",
    matchScore: 90,
    summary: "4 years full-stack, primarily the T3 stack. Built and launched three production SaaS apps.",
  },
  {
    id: "14",
    name: "Oscar Lindqvist",
    role: "DevOps Engineer",
    location: "Remote",
    experienceYears: 5,
    skills: ["Terraform", "GCP", "Docker", "Python", "Monitoring"],
    status: "Rejected",
    appliedDate: "2025-04-30",
    initials: "OL",
    matchScore: 61,
    summary: "5 years DevOps on GCP. Limited AWS experience which was a requirement for this role.",
  },
  {
    id: "15",
    name: "Fatima Al-Hassan",
    role: "Product Manager",
    location: "Birmingham",
    experienceYears: 8,
    skills: ["Strategy", "Agile", "OKRs", "Data Analysis", "Stakeholder Management"],
    status: "Interview",
    appliedDate: "2025-05-03",
    initials: "FA",
    matchScore: 87,
    summary: "8 years PM, from IC to Head of Product. Deep experience running discovery in complex domains.",
  },
];

export const SUGGESTED_PROMPTS = [
  "Senior frontend developer with React and TypeScript, based in London",
  "Junior backend engineer with Node.js experience, open to remote",
  "Product designer with Figma and design systems experience",
  "Full-stack developer with Next.js and PostgreSQL, 3–6 years experience",
  "DevOps engineer with Kubernetes and AWS, any location",
];
